
name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 14.x, 16.x ]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm ci

    - name: Analyze code using Lint
      uses: sibiraj-s/action-eslint@v2
      with:
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js,jsx,ts,tsx'
        annotations: true

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker Container Deployment to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}